name             'handson'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures handson'
long_description 'Installs/Configures handson'
version          '0.1.0'
